# Site settings
title: MAYDAY.US
email: info@mayone.us
description: "MAYDAY.US - A Crowdfunded, Kickstarted SuperPAC to end all SuperPACs"
baseurl: /homepage_redesign

# Build settings
encoding: utf-8
markdown: kramdown
permalink: pretty
