# Site settings
title: MayOne.US
email: info@mayone.us
description: "MayOne.US - SuperPAC to end all SuperPACs. Join our effort to win a Congress committed to reforming the influence of money in Politics."
baseurl: /redesign_jekyll

# Build settings
markdown: kramdown
permalink: pretty